export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DashboardPage } from './DashboardPage'
export { default as EditorPage } from './EditorPage'
export { default as TemplatesPage } from './TemplatesPage'
export { default as SettingsPage } from './SettingsPage'
